microsoftgraph/msgraph-sdk-powershell

config/AutoRestConfig.yml
tools/DownloadOpenAPIDoc.ps1
tools/GenerateModules.ps1

Also updated to use the new Beta Autorest

Fix to sharepointIds

---

samples/4-UsersAndGroups.ps1

This PR updates the `-PasswordProfile` parameter on `New-MgUser` Sample.

UsersAndGroups Sample Update

---

samples/8-ConditionalAccess.ps1

This is a sample to show minimum required parameters to create a CA policy

Adding sample script for creation of conditional access policy

---

.azure-pipelines/generate-auth-module-template.yml
src/Authentication/Authentication.Test/Helpers/AuthenticationHelpersTests.cs
src/Authentication/Authentication.Test/Helpers/ODataQueryOptionsHandlerTests.cs
src/Authentication/Authentication.Test/Microsoft.Graph.Authentication.Test.csproj
src/Authentication/Authentication/Helpers/ODataQueryOptionsHandler.cs

This PR:
- Removes leading ? from query when appending a query to UriBuilder.
- Updates unit test to validate the change.
relates to #408 and #409

Remove leading ? from query option on PS 5.1.

---

samples/9-Applications.ps1

Fix reference to variable ($app4) of created application registration for "ClientCredentialApp"

Fix reference to ClientCredentialApp for SPN

---

README.md

Fix Mg prefix and some minor typos.

Fix Mg prefix and some minor typos

---

README.md

Add section of Known Issues to main readme file.  Also add known issue with PowerShell ISE and recommendation to use an alternate host.

Add section of Known Issues

---

src/Authentication/Authentication.Test/Helpers/StringUtilTests.cs
src/Authentication/Authentication/Helpers/StringUtil.cs

Return case Insensitive dictionaries from Invoke-MgGraphRequest.
Add tests to verify bugfix.
fixes #421

Return case insensitive dictionaries from IMGR.

---

openApiDocs/beta/Identity.DirectoryManagement.yml
openApiDocs/beta/Teams.yml
openApiDocs/v1.0/Teams.yml

This PR updates the OpenAPI docs with the latest modules mapping, which adds previously missing paths.

Update OpenApi Docs

---

src/Authentication/Authentication/Microsoft.Graph.Authentication.psd1
src/DirectoryObjects/DirectoryObjects/readme.md
src/Financials/Financials/readme.md
src/Identity.Governance/Identity.Governance/readme.md

This PR:
- Updates remove directive declaration for agreementFile cmdlets in `Identity.Governance` module .
- Bumps the version of all modules to `1.4.3`.

Update agreementFile remove directive

---

config/ModulesMapping.jsonc
openApiDocs/beta/Sites.yml
openApiDocs/v1.0/Sites.yml
profiles/Sites/crawl-log-v1.0-beta.json
profiles/Sites/crawl-log-v1.0.json
profiles/Sites/definitions/v1.0-beta.md
profiles/Sites/definitions/v1.0.md
tools/GenerateProfiles.ps1

This PR partly addresses #600 by adding missing sites permissions API. Part two of the issue will be addressed by https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/509.

Adds missing site permissions to sites module

---

config/ModuleMetadata.json
src/Applications/Applications/readme.md
src/CloudCommunications/CloudCommunications/readme.md
src/Compliance/Compliance/readme.md
src/DeviceManagement.Actions/DeviceManagement.Actions/readme.md
src/DeviceManagement.Administration/DeviceManagement.Administration/readme.md
src/DeviceManagement.Enrolment/DeviceManagement.Enrolment/readme.md
src/DeviceManagement.Functions/DeviceManagement.Functions/readme.md
src/DeviceManagement/DeviceManagement/readme.md
src/Devices.CloudPrint/Devices.CloudPrint/readme.md
src/Devices.CorporateManagement/Devices.CorporateManagement/readme.md
src/Education/Education/readme.md
src/Files/Files/readme.md
src/Groups/Groups/readme.md
src/Identity.Governance/Identity.Governance/readme.md
src/Identity.SignIns/Identity.SignIns/readme.md
src/Search/Search/readme.md
src/Sites/Sites/readme.md
src/Teams/Teams/readme.md
src/Users.Actions/Users.Actions/readme.md
src/Users.Functions/Users.Functions/readme.md
src/Users/Users/readme.md

This PR bumps the SDK version to 1.6.0 in readiness for 1.6.0 release.

Bump SDK version to 1.6.0

---

.github/workflows/create-helpdocs-pr-workflow.yml
.github/workflows/create-openapidocs-pr-workflow.yml

Docs PR Assignment

---

src/Authentication/Authentication/build-module.ps1
src/Authentication/Authentication/custom/FindMgGraph_Permission.ps1
src/Authentication/Authentication/custom/common/Permissions.ps1

Made sure the datasample file is included in the build and also expanding the search criteria from just names to names and descriptions

Data sample file part of build

---

.azure-pipelines/common-templates/download-openapi-docs.yml

Misnamed Template causing Pipeline Failure.

Misnamed Template Causing Pipeline failure

---

src/Authentication/Authentication/custom/Find-MgGraphPermission.ps1
src/Authentication/Authentication/custom/common/Permissions.ps1

Included the online switch case to it

Fehintola obafemi/permissions online

---

src/Authentication/Authentication/custom/Find-MgGraphPermission.ps1
src/Authentication/Authentication/test/Find-MgGraphPermission.Tests.ps1

Made spelling corrections and attempted to fix the error flagged by Peter. Also, made minor cosmetic changes to match Powershell's naming convention

Edits v0.1

---

.azure-pipelines/generation-templates/generate-command-metadata-template.yml
.azure-pipelines/generation-templates/generate-service-modules.yml

This PR fixes failing weekly OpenAPI download AzDo pipeline.

Update Weekly OpenAPI Download AzDo Pipeline

---

src/readme.graph.md

Update Autorest local version reference.

Update autorest local version.

---

src/Authentication/Authentication/Cmdlets/InvokeMgGraphRequest.cs
src/Authentication/Authentication/test/Invoke-MgGraphRequest.Tests.ps1

Adds missing support for relative URIs on Invoke-MgGraphRequest

---

.azure-pipelines/generation-templates/generate-helpdocs-template.yml
.azure-pipelines/integrated-pipeline.yml
.azure-pipelines/weekly-generation.yml

Change build agent.

---

.azure-pipelines/common-templates/security-prechecks-template.yml
.azure-pipelines/integrated-pipeline.yml

This PR closes #1246 by updating the AzDo pipeline scripts with the updated "main" branch name.

Rename master branch to main

---

Dockerfile

template for CD https://github.com/microsoft/kiota/blob/main/.github/workflows/docker.yml

 - adds docker image definition

---

src/Authentication/Authentication.Core/ErrorConstants.cs
src/Authentication/Authentication.Core/Utilities/AuthenticationHelpers.cs
src/Authentication/Authentication.Test/Helpers/AuthenticationHelpersTests.cs

This PR closes #936 by providing a certificate lookup implementation that looks for certificates in both the current user and local machine certificate store.

Current User and Local Machine Certificate Store Lookup

---

src/Identity.SignIns/Identity.SignIns/readme.md

Remove New/Update/Remove MgUserAuthenticationMethod

---

src/Identity.DirectoryManagement/Identity.DirectoryManagement/examples/v1.0/Get-MgDomainFederationConfiguration.md
src/Identity.DirectoryManagement/Identity.DirectoryManagement/examples/v1.0/New-MgDomainFederationConfiguration.md
src/Identity.DirectoryManagement/Identity.DirectoryManagement/examples/v1.0/Remove-MgDomainFederationConfiguration.md
src/Identity.DirectoryManagement/Identity.DirectoryManagement/examples/v1.0/Update-MgDomainFederationConfiguration.md

﻿
- Adding examples to cmdlets
-
-
-
-
-

Added examples to the domain federation v1.0 cmdlets

---

.azure-pipelines/common-templates/update-sdkversion.yml

﻿
Fixes #
This PR fixes the required modules step in the weekly examples embedding pipeline. The machine in which the pipeline is running does not recognize ``Get-InstalledModule Microsoft.Graph`` command which is an easier way to install the latest graph powershell sdk.
-      Get the first version of module from a list of Microsoft.Graph  and manually compare it with the latest version available on the powershell gallery.
-       Install the latest version if it is not available in the list

Examples Pipeline Required Module Step

---

.github/workflows/update_examples_pr_workflow.yml

﻿
Fixes #
Failures during github checks due to a wrong reviewer specified on the github action file for creating PR
- Only have reviewers who are collaborators

Collaborator update

---

README.md

This PR updates v1 readme with links to v2 upgrade guide.

Update v1 readme with links to v2 upgrade guide.

---

src/Teams/Teams/examples/v1.0-beta/Update-MgTeamworkTeamAppSetting.md

﻿
- Adding an example
-
-
-
-
-

Added a second example

---

.azure-pipelines/common-templates/download-openapi-docs.yml
.azure-pipelines/common-templates/update-sdkversion.yml
.azure-pipelines/generation-templates/generate-command-metadata-template.yml
.azure-pipelines/generation-templates/generate-helpdocs-template.yml
.azure-pipelines/generation-templates/generate-service-modules.yml
.azure-pipelines/weekly-examples-update.yml
scripts/create-pull-request.ps1
tools/ExamplesGenerator.ps1

This PR updates AzDo create PR tasks by adding a head branch option and using origin as the upstream.
See PR sample at https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/1887.

Updates create pull request task

---

src/Users.Functions/Users.Functions/test/v1.0/Get-MgUserDelta.Tests.ps1
src/readme.graph.md

[V2] Paging support for delta commands

---

tools/ExamplesGenerator.ps1

﻿
Fixes #2047  
This is the corresponding [PR](https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/2051)to validate this fix 
- The script ensures that extraction of external docs link parameter from open API file is method driven (GET, POST, DELETE, PATCH)
- The script also maintains correct examples and discards wrong examples.

[V1]Examples Generator Script Review

---

README.md
samples/5-Teams.ps1
samples/Scripts/Get-TeamMembers.ps1
src/Users.Actions/v1.0/examples/Set-MgUserLicense.md
tools/Tests/DebugTests.ps1

This PR updates the repo's readme and samples to show v2 examples.

Update Readme and Samples

---

.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/microsoft-graph-powershell-bug-report.md

Adds issue templates for bug reports and feature requests.

Adds issue templates

---

README.md
docs/authentication.md
docs/upgrade-to-v2.md

- A freshness pass for v2 readme and changelog to ensure everything is up-to-date.

V2 Readme Freshness Pass

---

src/Identity.DirectoryManagement/beta/examples/Get-MgBetaDomain.md
src/Identity.DirectoryManagement/v1.0/examples/Get-MgDomain.md

﻿
Fixes #
- Corrected a typo to an example title
-
-
-
-
-

Corrected a typo - Get-MgDomain

---

src/Authentication/Authentication/custom/Find-MgGraphCommand.ps1
src/Authentication/Authentication/test/Find-MgGraphCommand.Tests.ps1

Fixes #2306 
- Replaces /me path segments with /users/{user-id}

Translates /me to /users/{user-id}

---

config/ModuleMetadata.json
tools/Versions/SetModuleVersion.ps1

﻿
Fixes auto version increment by ensuring patch version is reset to 0 anytime the minor version is incremented.

Fix auto version increment

---

src/Authentication/descriptions/Add-MgEnvironment.md
src/Authentication/descriptions/Get-MgGraphOption.md
src/Authentication/descriptions/Get-MgRequestContext.md
src/Authentication/descriptions/Remove-MgEnvironment.md
src/Authentication/descriptions/Set-MgEnvironment.md
src/Authentication/descriptions/Set-MgGraphOption.md
src/Authentication/descriptions/Set-MgRequestContext.md
src/Authentication/docs/Add-MgEnvironment.md
src/Authentication/docs/Get-MgGraphOption.md
src/Authentication/docs/Get-MgRequestContext.md
src/Authentication/docs/Microsoft.Graph.Authentication.md
src/Authentication/docs/Remove-MgEnvironment.md
src/Authentication/docs/Set-MgEnvironment.md
src/Authentication/docs/Set-MgGraphOption.md
src/Authentication/docs/Set-MgRequestContext.md
src/Authentication/examples/Add-MgEnvironment.md
src/Authentication/examples/Get-MgGraphOption.md
src/Authentication/examples/Get-MgRequestContext.md
src/Authentication/examples/Remove-MgEnvironment.md
src/Authentication/examples/Set-MgEnvironment.md
src/Authentication/examples/Set-MgGraphOption.md
src/Authentication/examples/Set-MgRequestContext.md
src/Authentication/synopsis/Add-MgEnvironment.md
src/Authentication/synopsis/Get-MgGraphOption.md
src/Authentication/synopsis/Get-MgRequestContext.md
src/Authentication/synopsis/Remove-MgEnvironment.md
src/Authentication/synopsis/Set-MgEnvironment.md
src/Authentication/synopsis/Set-MgGraphOption.md
src/Authentication/synopsis/Set-MgRequestContext.md

Adds missing description, synopsis and examples for handwritten authentication cmdlets

---

src/Identity.DirectoryManagement/v1.0/examples/New-MgDirectoryRoleTemplate.md

Fixes https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/issues/397

Removed wrong example from New-MgDirectoryRoleTemplate cmdlet

---

src/Applications/v1.0/examples/Get-MgApplication.md

Reverting the main branch. The merge destination for this PR #2383 was supposed to be the dev branch.  This has been communicated to the author on this PR https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/pull/405 in the PowerShell reference docs repo.

Revert "Update Get-MgApplication.md permissions details."

---

src/Applications/beta/examples/Get-MgBetaApplication.md

Added specific Application permissions to Beta examples.
﻿
Fixes #
-
-
-
-
-
-

Added specific Application permissions to Beta examples.

---

src/Applications/v1.0/examples/Get-MgServicePrincipal.md

Update Get-MgServicePrincipal.md to specific Application permissions
﻿
Fixes #
-
-
-
-
-
-

Update Get-MgServicePrincipal.md to specific Application permissions

---

src/Applications/v1.0/examples/Get-MgApplication.md

Update specific permissions for the Applications v1.0 examples
﻿
Fixes #
-
-
-
-
-
-

Update specific permissions for the Applications v1.0 examples

---

src/Applications/beta/examples/Get-MgBetaServicePrincipal.md

Update Get-MgBetaServicePrincipal.md with specific Application permissions.
﻿
Fixes #
-
-
-
-
-
-

Update Get-MgBetaServicePrincipal.md with specific permissions

---

src/Groups/beta/examples/Get-MgBetaGroup.md

Update Get-MgBetaGroup.md specific permissions
﻿
Fixes #
-
-
-
-
-
-

Update Get-MgBetaGroup.md specific permissions

---

src/Groups/v1.0/examples/Get-MgGroup.md

Update Get-MgGroup.md specific permissions.
﻿
Fixes #
-
-
-
-
-
-

Update Get-MgGroup.md specific permissions.

---

src/Applications/beta/examples/Get-MgBetaApplicationDelta.md

Update Get-MgBetaApplicationDelta.md specific permissions.

---

src/Applications/v1.0/examples/Get-MgApplicationDelta.md

Update Get-MgApplicationDelta.md specific permissions

---

src/Teams/v1.0/examples/Update-MgTeamworkTeamAppSetting.md

Update-MgTeamworkTeamAppSetting Example

---

src/Authentication/Authentication/Microsoft.Graph.Authentication.nuspec

﻿
Fixes #2424 
- Adds missing System.Memory.Data.dll

Adds missing System.Memory.Data.dll

---

config/ModuleMetadata.json

Fixes #
Ships the sdk with missing System.Memory.Data.dll
- Bumps SDK version to 2.9.1

Bump sdk version to 2.9.1

---

.azure-pipelines/common-templates/install-tools.yml

- fixes #2535

---

src/Applications/beta/examples/Set-MgBetaApplicationConnectorGroupByRef.md

Updates exampleto match the powershell snippet in the API reference https://learn.microsoft.com/graph/api/connectorgroup-post-applications?view=graph-rest-1.0

Updates example for Set-MgBetaApplicationConnectorGroupByRef

---

openApiDocs/beta/Users.yml
openApiDocs/v1.0/Users.yml

Fixes #2613 
**What changed?**
1.  Updated open API files for users module.
2. Updated command metadata file to include ``Remove-MgUserPhoto`` and ``Remove-MgUserPhoto``

Updates Open API file for users module to include ``DELETE`` operation for ``/users/{user-id}/photo`` path

---

tools/OpenApiInfoGenerator/OpenApiInfoGenerator/Program.cs

﻿
Fixes #
- Points the urls to dev branch
-
-
-

Updates endpoint to metadata file for detecting changes

---

.github/workflows/project-auto-add.yml

Related to https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2428

Update language and project on issues and PRs

---

.github/policies/resourceManagement.yml

Related to https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2536

remove label waiting for author feedback if issue closes

---

.github/ISSUE_TEMPLATE/03-blank-issue.md
.github/ISSUE_TEMPLATE/config.yml

Related to https://github.com/microsoft/kiota-http-dotnet/issues/262

Disable blank issue template

---

config/ModuleMetadata.json

This PR is based on https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/2874 so that docker image is updated.

Patch for updating docker container

---

src/Security/beta/examples/New-MgBetaSecurityAuditLogQuery.md

fixed the indent on the example
﻿
Fixes #
-
-
-
-
-
-

Update New-MgBetaSecurityAuditLogQuery.md - fix example indent

---

.gitmodules

- Including the fixes made in https://github.com/microsoftgraph/autorest.powershell/pull/7
- Fixes branch name for future updates from `remote`

Bump autorest submodule

---

src/DeviceManagement.Enrollment/beta/examples/New-MgBetaRoleManagementCloudPcRoleDefinition.md
src/DeviceManagement.Enrollment/beta/examples/Update-MgBetaRoleManagementCloudPcRoleDefinition.md

Deletes incorrect header in ``New-MgBetaRoleManagementCloudPcRoleDefinition.md`` and ``Update-MgBetaRoleManagementCloudPcRoleDefinition.md``.

Removed Incorrect example header

---

src/Groups/v1.0/examples/Get-MgGroup.md

﻿
Fixes #[310723](https://dev.azure.com/msft-skilling/Content/_workitems/edit/310723): 
- Corrected an example title-
-
-
-

Corrected example 5 title

---

.azure-pipelines/ci-build.yml
.azure-pipelines/generation-templates/generate-helpdocs-template.yml
.azure-pipelines/weekly-generation.yml

﻿
Fixes #3004
- Updates pipeline to a pool hosted in Torus

Updates agent name from 1es-windows-ps-compute to 1es-windows-ps-comput-m

---

Dockerfile

Fix minor typo in Dockerfile

---

src/readme.graph.md

Set alias for Update-MgUser to Set-MgUser

---

src/Identity.Governance/Identity.Governance.md

Updates autorest to remove invalid `Remove-MgBetaEntitlementManagementAccessPackageAssignment`cmdlet

---

src/readme.graph.md

Adds AutoREST directive to set `*OnPremises*` as an alias for `*OnPremisess*`

---

.azure-pipelines/ci-build.yml

This PR adds a dependency on build stage for the docker push stage

Fix: Depend on previous stage

---

src/Authentication/Authentication.Core/Microsoft.Graph.Authentication.Core.csproj

Revert azure identity updates as more work needs to be done to fix dependency conflicts.

revert azure identity updates
