microsoftgraph/msgraph-sdk-powershell

- .azure-pipelines/generate-auth-module.yml
- .azure-pipelines/validate-pr-auth-module.yml
- .gitignore
- src/Authentication/Authentication.Test/Helpers/ODataQueryOptionsHandlerTests.cs
- src/Authentication/Authentication.Test/Microsoft.Graph.Authentication.Test.csproj
- src/Authentication/Authentication.Test/TestUtils/FakeSuccessHandler.cs
- src/Authentication/Authentication.sln
- src/Authentication/Authentication/Helpers/HttpHelpers.cs
- src/Authentication/Authentication/Helpers/ODataQueryOptionsHandler.cs
This PR adds `$` to standard OData[ query parameters](https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/c6d014a0c93893f920e2e1a4163989fcd51516c8/src/Authentication/Authentication/Helpers/ODataQueryOptionsHandler.cs#L19) targeting `v1.0` endpoint if non is set. On the v1.0, `$` is only optional on a subset of the APIs, and it's [recommended](https://docs.microsoft.com/en-us/graph/query-parameters) to always include `$` on query options targeting `v1.0` endpoint.
The prepending logic also ensures that the values set on query parameter are not modified, and `$` is only prepended to standard OData query options. This is validated by the unit tests.
Closes https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/22
> Add $ to v1.0 OData query options

- src/Authentication/Authentication/Constants.cs
- src/Authentication/Authentication/Helpers/AuthenticationHelpers.cs
- src/Authentication/Authentication/Properties/launchSettings.json
- src/Authentication/Authentication/TokenCache/TokenCryptographer.cs
- src/Authentication/Authentication/TokenCache/WindowsTokenCache.cs
This PR moves the token cache from the SDKs installation directory to a users profile.
The token will be saved in the following directories for these platforms:
| Windows | Linux | MacOS |
| ------------- |:-------------:| -----:|
| C:\Users\{USERNAME} | /home/{USERNAME} | /Users/{USERNAME} |
It closes https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/109
> Update Token Path To UserProfile

- src/readme.graph.md
This PR implements suggestions made in https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/97 by renaming the following query parameters and aliasing them with their OData name:
| Current Parameter Name  | New Parameter Name  | Alias  |
|---|---|---|
| OrderBy  | Sort  | OrderBy  |
| Top  | PageSize  | Top  |
| Select  | Property  | Select |
| Expand | ExpandProperty | Expand |
`Get-MGUser` signature:
Closes https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/97
> Rename OData query parameters to comply with PS vocabulary

- .azure-pipelines/generate-beta-modules.yml
- .azure-pipelines/generate-beta-rollup-module.yml
- .azure-pipelines/generate-v1.0-modules.yml
- .azure-pipelines/generate-v1.0-rollup-module.yml
- .azure-pipelines/validate-pr-beta-modules.yml
- .azure-pipelines/validate-pr-v1.0-modules.yml
- src/Authentication/Authentication/Microsoft.Graph.Authentication.psd1
- tools/BuildModule.ps1
- tools/GenerateModules.ps1
- tools/GenerateRollUpModule.ps1
- tools/NuspecHelper.ps1
This PR addresses issues that have been reported when running `Microsoft.Graph 0.5.0` on PowerShell 5.1.
Changes made:
- Update all ADO pipelines to use script variables instead of environment variables when generating modules.
- Specify dependency versions in module manifest.
Will fix #189, #187, #194
> PowerShell 5.1 hard dependency fix

- src/Authentication/Authentication.Test/Helpers/GraphSessionTests.cs
- src/Authentication/Authentication/Common/GraphSession.cs
- src/Authentication/Authentication/ErrorConstants.cs
As noted in #253, the current design of `GraphSession` only works for single-threaded scenarios, but throws an exception for multi-threaded scenarios. This PR updates authentication module by reusing the existing session object, if one is found, as opposed to throwing an exception. The session object will only be initialized once `OnImport`, and subsequent calls will reuse the previously instantiated session.
> Multi-thread GraphSession support

- src/Authentication/Authentication/Cmdlets/InvokeGraphRequest.cs
- src/Authentication/Authentication/Helpers/Errors.cs
- src/Authentication/Authentication/Helpers/StringUtil.cs
- src/Authentication/Authentication/Properties/Resources.Designer.cs
- src/Authentication/Authentication/Properties/Resources.resx
Ensure that Connect-Graph has been prior called before IGR is called.
Change Headers to non-generic Dictionary.
Traverse nested json.
Add resource messages for error messages.
Provide ability to pass relative URL as well as query params.
fixes #296
> IGR Error Fixes

- src/Authentication/Authentication/Helpers/ContentHelper.cs
- src/Authentication/Authentication/Helpers/InvokeGraphRequestUserAgent.cs
- src/Authentication/Authentication/Microsoft.Graph.Authentication.csproj
Remove Microsoft.PowerShell.Commands.Utility  since it doesn't work in PS5. 
Remove references to Microsoft.PowerShell.Commands.Utility, and migrate to Platform helpers. 
#325
> Auth Module Dependencies

- src/Authentication/Authentication/Cmdlets/InvokeGraphRequest.cs
Powershell 5.0 does not allow GET Requests to have bodies.
https://github.com/PowerShell/PowerShell/issues/2054
Parse HashTables as Json, to enable requests to be made in the following structure. 
Correctly serialized as shown below
> Handle Dictionaries as Json and Powershell 5.0 GET Requests shouldn't have bodies.

- src/Authentication/Authentication/Cmdlets/InvokeGraphRequest.cs
* Powershell 5.0 does not allow GET Requests to have bodies.
Parse HashTables as Json.
* Null check for Content during Get Requests.
Co-authored-by: George
> Allow content to be null for GET Requests (#332)

- .azure-pipelines/generate-auth-module.yml
- .azure-pipelines/generate-beta-modules.yml
- .azure-pipelines/generate-beta-rollup-module.yml
- tools/GenerateAuthenticationModule.ps1
- tools/GenerateModules.ps1
- tools/GenerateRollUpModule.ps1
This PR address some of the pipeline issues that we experienced during the release on 0.9.1.
- Fixes broken paths in the pipeline scripts since we now generate each service version as a profile.
- Updates signing script to only sign the bare-minimum number of files. This reduces the current signing time from ~3+ hours to ~40 minutes.
> 0.9.1 Pipeline Fixes

- src/Financials/Financials/readme.md
- src/Identity.Organization/Identity.Organization/readme.md
- src/Teams.Team/Teams.Team/readme.md
- src/readme.graph.md
- tools/Custom/ListCmdlet.cs
- tools/Custom/Module.cs
- tools/GenerateModules.ps1
This PR contains bug fixes that have noted with the release of 0.9.1. Most of the bugs are caused by how AutoREST handles serialization and deserialization of additionalProperties. This PR applies directives to fix these issues in the interim, but we will also open corresponding issues in AutoREST's repo for a long-term fix. The following changes are proposed in the PR  :
- Adds a directive that excludes known properties of an entity from being serialized as key-value pairs in additionalProperties. This wasn't properly handled by AutoREST and would lead to duplicate key exception since a key would be serialized in two places, as entity property and in additionalProperties. This only happened when an entity and its base class both had an additionalProperties. Closes #339 .
Exclusions …
> 0.9.1 bug fixes

- src/readme.graph.md
- tools/Custom/ListCmdlet.cs
This PR closes #152 by proposing the following changes:
- Ensures all `$count=true` is always in lowercase. MS Graph doesn't support Camel cased count values.
- Adds a runtime `-CountVariable` parameter to all cmdlets that return a collection. This will be used by customers to get back a deserialized value of `@odata.count` returned in the response body. By default, this variable will be stored in the global scope.
- Adds `-CV` alias for `-CountVariable`.
- Makes `-Count` parameter private i.e. it won't be exposed to customers.
- Ensures `$count=true` is always set with `-CountVariable` is present.
> Add -CountVariable parameter

- src/Authentication/Authentication.Test/Helpers/AuthenticationHelpersTests.cs
- src/Authentication/Authentication/Cmdlets/ConnectGraph.cs
- src/Authentication/Authentication/Common/GraphSession.cs
- src/Authentication/Authentication/Constants.cs
- src/Authentication/Authentication/ErrorConstants.cs
- src/Authentication/Authentication/Helpers/AuthenticationHelpers.cs
- src/Authentication/Authentication/Helpers/HttpHelpers.cs
- src/Authentication/Authentication/Helpers/JwtHelpers.cs
- src/Authentication/Authentication/Interfaces/IAuthContext.cs
- src/Authentication/Authentication/Models/JwtPayload.cs
- src/Authentication/Authentication/TokenCache/TokenCacheStorage.cs
This PR adds `-accessToken` to `Connect-Graph`. The access token lives in the session object and the customer will have to handle its refresh by calling `Connect-Graph -AccessToken "NEW_TOKEN"`.
Closes #335
> Add -AccessToken parameter to Connect-Graph

- src/Authentication/Authentication/Cmdlets/ConnectGraph.cs
- src/Authentication/Authentication/Cmdlets/ConnectMgGraph.cs
- src/Authentication/Authentication/Cmdlets/DisconnectMgGraph.cs
- src/Authentication/Authentication/Cmdlets/InvokeMgGraphRequest.cs
- src/Authentication/Authentication/Helpers/HttpHelpers.cs
- src/Authentication/Authentication/Helpers/PathUtils.cs
- src/Authentication/Authentication/Helpers/StreamHelper.cs
- src/Authentication/Authentication/Microsoft.Graph.Authentication.psd1
This PR proposed the following changes:
1. Renames `Connect-Graph` and `Disconnect-Graph` to `Connect-MgGraph` and `Disconnect-MgGraph` respectively. Their old names are then use as aliases to avoid breaking change. See customer ask https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/142#issuecomment-606776307.
2. Adds support for comma separates scopes. This was previously broken. Closes https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/381.
- Should we also alias `Invoke-GraphRequest`? If so, what name should we use.
> Connect and Disconnect-Graph Aliases

- config/ModulesMapping.jsonc
- src/Applications/Applications/readme.md
- src/Authentication/Authentication/Common/DiskDataStore.cs
- src/Authentication/Authentication/Common/ProtectedFileProvider.cs
- src/Files/Files/readme.md
- src/readme.graph.md
- tools/Custom/FileUploadCmdlet.cs
- tools/Custom/PSCmdletExtensions.cs
This PR proposes the following changes to properly handle file upload and download with the generated commands.
1. Adds `FileUploadCmdlet` class. This will be the base class for all cmdlets that upload files i.e. `-BodyParameter` is of type `Stream` and name starts with `Set-*`. `FileUploadCmdlet` class performs the following :
- Adds a mandatory `-InFile` parameter to all cmdlets that derive from `FileUploadCmdlet`.
- `GetFileAsStream` handles getting a resolved path to the file and returns a thread safe stream.
2. Adds `PSCmdletExtensions` class. This class provides helper methods that handle retrieval of valid paths and writing of streams to a file on disk.
3. Adds directives to replace broken file upload and download logic in generated cmdlets. 
For file download, the directive:
- Add …
> Stream Support Improvements

- src/readme.graph.md
- tools/Custom/ListCmdlet.cs
In order to support KQL, `$Search` values should be surrounded by `" "`. This PR adds `FormatSearchValue` method that adds double quote marks around $search values if none exists.
Closes #399 #402 #419
> Format Search Values

- src/Authentication/Authentication/Cmdlets/InvokeMgGraphRequest.cs
***Original Issue***
https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/390706e3cbc026fc9f37267c8dd6cb2caad04c99/src/Authentication/Authentication/Cmdlets/InvokeMgGraphRequest.cs#L664-L672
Line above only defaulted the `Content-Type` to `application/json` for `POST` only.
****Fix****
Set default Content-Type header to application/json when user has not specified `-ContentType` for `PUT,POST,PATCH` requests.
Fixes #483
> Bug: Invoke-GraphRequest fails with BadRequest for PUT Requests

- .azure-pipelines/generate-beta-modules.yml
- .azure-pipelines/generate-modules-template.yml
- .azure-pipelines/validate-pr-beta-modules.yml
- build.proj
- src/Applications/Applications/test/Applications.Tests.ps1
- src/CloudCommunications/CloudCommunications/test/CloudCommunications.Tests.ps1
- src/Users/Users/test/Users.Tests.ps1
- tools/GenerateModules.ps1
- tools/TestModule.ps1
This PR closes #373 by replacing all instances of `Write-Information` in a module (.psm1) with `Write-Debug`. This frees up the information stream since everything will be logged in the debug stream when `$DebugPreference` is set to `inquire` or `Continue`.
``` powershell
$ps = [powershell]::Create()
$ps.AddScript(@'
Connect-MgGraph -CertificateThumbprint $certificateThumbprint -ClientId $appId -TenantId $tenantNameOrId
$Users = Get-MgUser -Top 5
'@).Invoke()
$ps.Streams.Information
$ps.Streams.Debug
```
``` powershell
$ps = [powershell]::Create()
$ps.AddScript(@'
$DebugPreference = "Inquire"
Connect-MgGraph -CertificateThumbprint $certificateThumbprint -ClientId $appId -TenantId $tenantNameOrId
$Users = Get-MgUser -Top 5
'@).Invoke()
$ps.Streams.Information
$ps.Streams.Debug
```
> Information Stream Cleanup

- src/Authentication/Authentication/Microsoft.Graph.Authentication.psd1
- src/DeviceManagement.Actions/DeviceManagement.Actions/readme.md
- src/DeviceManagement.Administration/DeviceManagement.Administration/readme.md
- src/DeviceManagement.Functions/DeviceManagement.Functions/readme.md
- src/DeviceManagement/DeviceManagement/readme.md
- src/Devices.CorporateManagement/Devices.CorporateManagement/readme.md
- src/Financials/Financials/readme.md
- src/Notes/Notes/readme.md
This PR bumps the version of all modules that didn't have a change to 1.3.2 for release. This won't be necessary once we address our branching story. 
- Refreshes modules with latest APIs #561.
- Adds `DeviceManagement`, `DeviceManagement.Administration`, `DeviceManagement.Enrolment`, `DeviceManagement.Actions`, and `DeviceManagement.Functions` modules to the SDK #549.
- Fixes wrong count value with certain commands when a single item is returned in a collection #542.
- Fixes bug where `Connect-MgGraph` would truncate and try to use an invalid certificate thumbprint #540.
- Fixes `-AccessToken` parameter set #540,
- Removes breaking undocumented commands from Compliance module #552.
- Removes breaking undocumented commands from Devices.CorporateManagement module #565.
- Removes invalid …
> 1.3.2 Pre-Releases

- src/Sites/Sites/readme.md
- src/Sites/Sites/test/env.json
- src/Sites/Sites/test/loadEnv.ps1
- src/Sites/Sites/test/v1.0-beta/Get-MgSite.Recording.json
- src/Sites/Sites/test/v1.0-beta/Get-MgSite.Tests.ps1
- src/Sites/Sites/test/v1.0-beta/Get-MgSiteByPath.Recording.json
- src/Sites/Sites/test/v1.0-beta/Get-MgSiteByPath.Tests.ps1
- src/Sites/Sites/test/v1.0-beta/Get-MgSubSite.Recording.json
- src/Sites/Sites/test/v1.0-beta/Get-MgSubSite.Tests.ps1
- src/Sites/Sites/test/v1.0/Get-MgSite.Recording.json
- src/Sites/Sites/test/v1.0/Get-MgSite.Tests.ps1
- src/Sites/Sites/test/v1.0/Get-MgSiteByPath.Recording.json
- src/Sites/Sites/test/v1.0/Get-MgSiteByPath.Tests.ps1
- src/Sites/Sites/test/v1.0/Get-MgSubSite.Recording.json
- src/Sites/Sites/test/v1.0/Get-MgSubSite.Tests.ps1
- tools/TestModule.ps1
- tools/Tests/loadEnv.ps1
This PR closes #573 by updating cmdlet rename directives in Sites module to use new cmdlet variants. 
For some unknown reason, some variants in Sites module got renamed which caused #573. I'm still waiting for an answer from https://github.com/Azure/autorest.powershell/issues/752 to understand what conditions can lead to a variant name change.
In the meantime, this PR adds Pester tests that will allow us to detect variant name change in the future.
> Fix broken commands in Sites module.

- .azure-pipelines/common-templates/download-openapi-docs.yml
- .azure-pipelines/generate-auth-module-template.yml
- .azure-pipelines/generate-modules-template.yml
- .azure-pipelines/generate-rollup-module-template.yml
- .azure-pipelines/generation-templates/generate-service-modules.yml
- .azure-pipelines/install-tools-template.yml
- .azure-pipelines/integrated-pipeline.yml
- .azure-pipelines/security-postchecks-template.yml
- .azure-pipelines/security-prechecks-template.yml
- .azure-pipelines/weekly-generation.yml
Add Build Agents Parameter to allow selecting build agent during runs.
> Add build agents parameter

- src/Authentication/Authentication/Microsoft.Graph.Authentication.psm1
This PR closes #641 by loading our dependency types to the current PowerShell session when a module is imported.
> Resolve dependency conflict with MSOnline module

- .github/CODEOWNERS
- .github/workflows/main.yml
This PR add a [CODEOWNERS](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners#about-code-owners) file to make PRs discoverable.
> Add CODEOWNERS to make PRs discoverable.

- src/Identity.Governance/Identity.Governance/readme.md
This particular function will not be brought forward into 1.0 Graph API, so suppress generation of PSh for it while it is in beta.
```
<Function Name="My" IsBound="true">
<Parameter Name="bindingParameter" Type="Collection(graph.accessPackageAssignmentResourceRole)" />
<ReturnType Type="Collection(graph.accessPackageAssignmentResourceRole)" />
</Function>
```
> Identity governance: suppress invoke of my() for accesspackageassignmentresourcerole

- tools/Custom/Module.cs
Handle case where network is down or the endpoint is unreachable making ResponseMessage null.
Earlier behavior would suppress network errors.
***Current Behavior***
Suppresses network errors throws `ArgumentNullException` in `HttpMessageFormatter`
***Proposed Behavior***
When network errors occur, let them propagate to Cmdlet Error handling.
> Handle case where network is down or the endpoint is unreachable

- samples/2-ConnectToGraph.ps1
- samples/9-Applications.ps1
- src/Authentication/Authentication/custom/Find-MgGraphPermission.ps1
- src/Authentication/Authentication/test/Find-MgGraphPermission.Tests.ps1
This change adds the following capabilities for `Find-MgGraphPermission`:
* New parameters for `Find-MgGraphPermission` to get more specific results and improve use in automation:
* `ExactMatch` option is useful when you know the permission name and just want information. This could really be part of a `Get-MgGraphPermission` command, but it seems unnecessary to introduce that when `Find-MgGraphPermission` basically does this. Most common use case here will be automation where you use friendly permission names and need to convert them to unique id's for use with commands / APIs that expect unique id's.
* `PermissionType` lets you filter on whether you want delegated or application permissions. This is useful because even in the `ExactMatch` case, permission names can map to multiple …
> Additional search filters for Find-MgGraphPermission, pipeline support, docs, samples

- .azure-pipelines/generate-modules-template.yml
- .azure-pipelines/generation-templates/generate-service-modules.yml
- tools/BuildModule.ps1
- tools/GenerateModules.ps1
The `.Notes` Section causes Nuget Packages and the SDK in general to bloat heavily. Excluding the `.Notes` section of the local help yields approximately **41pc** size reduction in module size reducing download and installation time. 
This PR keeps the Notes section information in the online docs, and excludes them from the local help. 
***Structure***
***Largest Reductions***
Name | Old Size | New Size | % Change | Difference
-- | -- | -- | -- | --
Microsoft.Graph.Files.1.6.1.nupkg | 31.4 MB | 5.1 MB | 83 | 26.4 MB
Microsoft.Graph.Sites.1.6.1.nupkg | 17.6 MB | 4.0 MB | 77 | 13.6 MB
Microsoft.Graph.Education.1.6.1.nupkg | 8.6 MB | 4.3 MB | 50 | 4.3 MB
Microsoft.Graph.Compliance.1.6.1.nupkg | 5.2 MB | 2.6 MB | 50 | 2.6 MB
Microsoft.Graph.DeviceManagement.1.6.1.nupkg | 15.5 MB | 8.4 MB | 46 …
> Introduce capability to Exclude .Notes Section from ProxyCmdletsDefinitions.ps1

- src/Authentication/Authentication.Core/Interfaces/IAuthContext.cs
- src/Authentication/Authentication/Cmdlets/ConnectMgGraph.cs
- src/Authentication/Authentication/Cmdlets/InvokeMgGraphRequest.cs
- src/Authentication/Authentication/Helpers/HttpHelpers.cs
- src/Authentication/Authentication/Helpers/RequestUserAgent.cs
- src/Authentication/Authentication/Models/AuthContext.cs
- tools/Custom/Module.cs
[Certain APIs](https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/630) require a `User-Agent` header to be present in the headers when making a request. This PR pre-populates `User-Agent` header for all requests made through the SDK.
The `User-Agent` will consist of:
- OS name and version.
- PowerShell host version.
- Command name.
Closes #630 
Closes #920
> Pre-populate User-Agent header for requests

- src/Authentication/Authentication/Cmdlets/ConnectMgGraph.cs
- src/Authentication/Authentication/Common/DiskDataStore.cs
This PR fixes the following bugs by:
- Closes #745 by defaulting to process scope on WSL. WSL instances don't come with secret-service installed that our token cache uses. Docker containers also run on WSL.
- Closes #888 by ensuring the `.graph` directory exists before attempting to read/write to files in the directory.
> Authentication Bug Fixes

- src/readme.graph.md
Use new version of autorest powershell where:-
- License text is not repeated in ProxyCmdlet definitions.
- Correct message pointing users to correct place to find help.
[Autorest.PowerShell fix](https://github.com/Azure/autorest.powershell/pull/874)
> Fix missing NOTES section reference with better message. 

- src/Authentication/Authentication/Constants.cs
https://github.com/microsoftgraph/msgraph-sdk-design/blob/master/middleware/TelemetryHandler.md
> Update SdkVersion format

- src/Authentication/Authentication/Constants.cs
- src/readme.graph.md
- tools/Custom/HttpMessageLogFormatter.cs
- tools/Custom/Module.cs
This PR ensures request/response bodies are always logged when `-Debug` is set.
> Properly handle async calls when logging request/response bodies

- .azure-pipelines/generate-modules-template.yml
- .azure-pipelines/integrated-pipeline.yml
- src/Identity.SignIns/Identity.SignIns/test/v1.0-beta/New-MgIdentityConditionalAccessNamedLocation.Recording.json
- src/Identity.SignIns/Identity.SignIns/test/v1.0-beta/New-MgIdentityConditionalAccessNamedLocation.Tests.ps1
- src/Identity.SignIns/Identity.SignIns/test/v1.0/New-MgIdentityConditionalAccessNamedLocation.Recording.json
- src/Identity.SignIns/Identity.SignIns/test/v1.0/New-MgIdentityConditionalAccessNamedLocation.Tests.ps1
- src/Sites/Sites/test/v1.0-beta/Get-MgSubSite.Tests.ps1
- src/Sites/Sites/test/v1.0-beta/New-MgSiteListItem.Recording.json
- src/Sites/Sites/test/v1.0-beta/New-MgSiteListItem.Tests.ps1
- src/Sites/Sites/test/v1.0/Get-MgSiteByPath.Tests.ps1
- src/Sites/Sites/test/v1.0/Get-MgSubSite.Tests.ps1
- src/Sites/Sites/test/v1.0/New-MgSiteListItem.Recording.json
- src/Sites/Sites/test/v1.0/New-MgSiteListItem.Tests.ps1
- src/readme.graph.md
This PR fixes #1185 by ensuring we only camelCase property names of derived types of NamedLocation (abstract type).
> Fix serialization of OpenTypes

- src/Authentication/Authentication/ErrorConstants.cs
- src/readme.graph.md
- tools/Custom/PSCmdletExtensions.cs
This PR closes #407 by adding a custom directive to download files when the response is of type `OctetStreamSchemaResponse` or `MicrosoftGraphReport`, and a command has `-OutFile` parameter.
``` powershell
Get-MgReportTeamUserActivityCount -Period D7 -OutFile "C:\My_PATH\FileName.csv"
Get-MgReportTeamUserActivityCount -Period D7 -OutFile "C:\My_PATH"
Get-MgReportTeamUserActivityCount -Period D7 -OutFile "FileName.csv"
Get-MgReportTeamUserActivityCount -Period D7 -OutFile .
```
> Add custom directive to download files in Reports module.

- src/Identity.DirectoryManagement/Identity.DirectoryManagement/docs/v1.0/Get-MgDomain.md
Fixed the "domaim" typo in "[Example 1](https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.identity.directorymanagement/get-mgdomain?view=graph-powershell-1.0#examples)" for the Get-MgDomain documentation. 
Fixes #1334 
- Initial text in doc: "Example 1: Get a list of domaim objects"
- Fixed text in doc: "Example 1: Get a list of domain objects"
- https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.identity.directorymanagement/get-mgdomain?view=graph-powershell-1.0#examples
> Fixed typo in Get-MgDomain example

- .azure-pipelines/integrated-pipeline.yml
This PR excludes from `features/2.0` branch from v1 integration builds as the branch has its own dedicated AzDo pipeline - https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/1435.
> Exclude features branch

- openApiDocs/beta/Applications.yml
- openApiDocs/beta/CrossDeviceExperiences.yml
- openApiDocs/beta/Devices.CloudPrint.yml
- openApiDocs/beta/Education.yml
- openApiDocs/beta/Groups.yml
- openApiDocs/beta/Identity.DirectoryManagement.yml
- openApiDocs/beta/Identity.Governance.yml
- openApiDocs/beta/Identity.SignIns.yml
- openApiDocs/beta/Users.yml
- openApiDocs/v1.0/Applications.yml
- openApiDocs/v1.0/Devices.CloudPrint.yml
- openApiDocs/v1.0/Education.yml
- openApiDocs/v1.0/Groups.yml
- openApiDocs/v1.0/Identity.DirectoryManagement.yml
- openApiDocs/v1.0/Identity.Governance.yml
- openApiDocs/v1.0/Identity.SignIns.yml
- openApiDocs/v1.0/Users.yml
This PR closes #1440 by temporarily adding missing request bodies to affected `/$ref` operations. The complete fix will be provided by https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/1082 once the bug fix is released.
> Manually add request bodies to ref operations

- src/Users/Users/examples/v1.0-beta/Get-MgUser.md
- src/Users/Users/examples/v1.0/Get-MgUser.md
﻿
Fixes #1469 
- Updated example 1
-
-
-
-
-
> Updated example 1 in Get-MgUser

- .azure-pipelines/common-templates/download-openapi-docs.yml
- .azure-pipelines/generation-templates/generate-service-modules.yml
- .azure-pipelines/integrated-pipeline.yml
- tools/GenerateHelp.ps1
This PR excludes v2 branch from v1 CI/CD by adding an `include` for `main` and `dev` branches during PR trigger.
The PR also reduces the number of commits made during `Docs Generation` automated PR generation. See https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/1564/commits.
> Exclude v2 branch from v1 CI/CD

- tools/TweakOpenApi.ps1
This PR closes #1605 by adding a pre-generation script that marks all navigation properties as readOnly. See discussion at https://github.com/microsoft/OpenAPI.NET.OData/issues/254 for more details.
The script will be executed every week after the weekly OpenAPI document refresh task is complete in https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/7abf06334a79538e8b17da123ec6e8f7d8d6a866/tools/UpdateOpenApi.ps1#L62
A complete diff of changes being made can be found at https://github.com/microsoftgraph/msgraph-sdk-powershell/compare/po/ReadOnlyNavProperties...testRun/ReadOnlyNavProperties.
> Mark nav properties as `readOnly`

- src/readme.graph.md
This PR fixes #1613 by changing the AutoREST generated code to use an indexer when adding nodes to a JsonObject. The old implementation would result in duplicate error as the `Add` method was called several times by AutoREST for a given JsonObject instance.
> Use indexer to add JsonObject node.

- src/Identity.Governance/Identity.Governance/custom/New-MgEntitlementManagementAccessPackageAssignmentRequest.ps1
This PR fixes #1618 by using the `beta` type of `AccessPackageAssignment.Target` property.
> Fix type reference of AccessPackageAssignment.Target property.

- .azure-pipelines/generation-templates/authentication-module.yml
- .azure-pipelines/generation-templates/meta-module.yml
- .azure-pipelines/generation-templates/workload-modules.yml
Fixes #1612 by ensuring we sign all module artifacts. The PR also adds a validation task to for all modules to ensure we've signed all `.psm1` and `psd1` files.
> Sign all module artifacts

- src/Authentication/Authentication/Cmdlets/ConnectMgGraph.cs
- src/Authentication/Authentication/Cmdlets/DisconnectMgGraph.cs
- src/Authentication/Authentication/Cmdlets/Environment/AddMgEnvironment.cs
- src/Authentication/Authentication/Cmdlets/Environment/GetMgEnvironment.cs
- src/Authentication/Authentication/Cmdlets/Environment/RemoveMgEnvironment.cs
- src/Authentication/Authentication/Cmdlets/Environment/SetMgEnvironment.cs
- src/Authentication/Authentication/Cmdlets/GetMGContext.cs
- src/Authentication/Authentication/Cmdlets/InvokeMgGraphRequest.cs
- src/Authentication/Authentication/custom/Find-MgGraphCommand.ps1
- src/Authentication/Authentication/custom/Find-MgGraphPermission.ps1
- src/Authentication/Authentication/custom/ParameterCompleters.ps1
This PR closes #1413 by adding `HelpUri` to commands in Authentication module. This should allow customers to open online command reference for commands in Authentication module. e.g., `Get-Help Connect-MgGraph -Online`.
> Adds HelpUri to commands in Authentication module.

- tools/ExamplesGenerator.ps1
This PR fixes an intermittent bug when fetching URI value result from Find-MgGraphCommand.
The value is used to fetch the external docs url from openapi docs. That url to scrap for examples from the api reference site.
> Bug fix on example generator

- src/Authentication/Authentication/Helpers/HttpHelpers.cs
- src/Users/v1.0/test/Users.Tests.ps1
This PR ensures we always throw the correct error message when AuthContext is null. The PR also adds a Pester test to validate the check.
> Throw Connect-MgGraph required when auth session in null.

- src/Authentication/Authentication/Helpers/ContentHelper.cs
- src/Authentication/Authentication/Helpers/CustomAsyncCommandRuntime.cs
- src/Authentication/Authentication/Helpers/StreamHelper.cs
- src/Authentication/Authentication/Helpers/StringUtil.cs
Fixes #1757 by applying changes made in #1764.
The fix will go as part of next week's release.
> Switch to UTF8 as the default encoding for `Invoke-MgGraphRequest`.

- src/Authentication/Authentication/custom/common/Permissions.ps1
- src/Authentication/Authentication/test/Find-MgGraphPermission.Tests.ps1
This PR fixes #1778 by using a local permissions cache when `AuthenticationException` is thrown. In v2, an `AuthenticationException` type will be thrown when executing a command without a connection to MS Graph.
> Updates `Find-MgGraphPermission` to a local cache when no connection to MS Graph exists

- src/readme.graph.md
- tools/Custom/PSCmdletExtensions.cs
This PR fixes #1339 by adding a directive to decode `$filter` values before encoding. This is done to avoid encoding an already encoded `$filter` value.
> Unescape filter values

- src/Authentication/Authentication.Core/Constants.cs
- src/Authentication/Authentication.Core/Microsoft.Graph.Authentication.Core.csproj
- src/Authentication/Authentication.Core/Utilities/AuthenticationHelpers.cs
- src/Authentication/Authentication.Core/Utilities/AzureIdentityAuthProvider.cs
- src/Authentication/Authentication.Test/Helpers/AuthenticationHelpersTests.cs
- src/Authentication/Authentication/Utilities/DependencyAssemblyResolver.cs
This PR fixes #1741 and fixes #1105 by:
- Adds `AzureIdentityAuthProvider` class which handles claims challenge by extracting claims from `ICaeAuthenticationProviderOption`. See https://learn.microsoft.com/en-us/azure/active-directory/develop/claims-challenge?tabs=dotnet.
- Updates dependencies to the latest version.
> Adds AzureIdentityAuthProvider for handling claims challenge

- src/Authentication/Authentication/test/Find-MgGraphCommand.Tests.ps1
﻿
Fixes #
Failing test which expects a collection of 1 but gets 2 .
[Failing pipeline](https://dev.azure.com/microsoftgraph/Graph%20Developer%20Experiences/_build/results?buildId=107258&view=logs&j=8237f910-645d-5a3a-aca0-8882f2669c51&t=ce4fbf81-c96e-55fb-0e09-e4dfd396271a)
Without specifying the api version, the test outputs both beta and v1.0 results hence making the test fail
- Added ```-ApiVersion beta``` parameter to default the collection size to 1 as per the test expectation
> Add beta api version parameter to the failing pester test. [v2.0]

- src/Authentication/Authentication/test/Connect-MgGraph.Tests.ps1
﻿
Fixes #
AZ.Accounts module failure as described [here](https://dev.azure.com/microsoftgraph/Graph%20Developer%20Experiences/_build/results?buildId=108079&view=logs&j=8237f910-645d-5a3a-aca0-8882f2669c51&t=ce4fbf81-c96e-55fb-0e09-e4dfd396271a)
- Added AllowClober parameter to overwrite the existing old modules
- Modified check to determine if AZ.Accounts module is already installed. The check uses "Count" to get the number of modules installed
> Connect-MgGraph Test (AZ.Accounts Module installation) fix

- src/Authentication/Authentication/custom/Find-MgGraphCommand.ps1
Fixes #
- Fix legacy command resolution on Windows PowerShell 5.x
-
-
-
-
-
> fix legacy command resolution on win ps 5.1

- config/ModuleMetadata.json
- src/Authentication/Authentication.Core/Models/JwtPayload.cs
This PR fixes #1901 by switching to `Syste.Text.Json`'s `JsonPropertyName` attribute for claims property names.
> Fixes Token Claims Decoding

- src/readme.graph.md
This PR fixes https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1931 by adding a directive to change the content type for OData count paths from `text/plain` to `application/json`. This is needed to due to https://github.com/Azure/autorest.powershell/issues/206.
The PR also adds parameter completer for `-ConsistencyLevel`.
Depends on https://github.com/microsoftgraph/microsoft-graph-devx-api/pull/1480.
> Adds OData count paths support

- src/Identity.Governance/Identity.Governance/custom/New-MgEntitlementManagementAccessPackageAssignment.ps1
﻿
Fixes #1726 
- An access package assignment policy can have a start date in the future, not known to the client.  By defaulting an absent start date field to the current date, those requests will fail unnecessarily. 
-
-
-
> Identity Governance customization: remove StartDate default when creating new assignment request

- src/Authentication/Authentication.Test/Handlers/ODataQueryOptionsHandlerTests.cs
- src/Authentication/Authentication/Handlers/ODataQueryOptionsHandler.cs
Fixes #1893
- Updates OData query options middleware handler to add `$` to OData query parameters for all API versions. This is needed to support beta commands in China cloud.
- Updates unit test to reflect the change.
> Adds `$` to OData query parameters for all API versions

- tools/ExamplesGenerator.ps1
﻿
Fixes #
Pipeline run failures due to missing psd1 files on some modules.
- Removes section where it validates availability from a modules psd1 file since we are already fetching commands from mgcommandmetadata.json file
> Validate availability of a commandlet only once from metadata file

- .azure-pipelines/common-templates/download-openapi-docs.yml
- config/ModuleMetadata.json
- src/readme.graph.md
- tools/BuildModule.ps1
- tools/Versions/BumpModuleVersion.ps1
- tools/Versions/SetModuleVersion.ps1
This PR bumps v2 preview version to RC status. RC1 brings the following fixes and updates to preview9:
* Fixes command names for commands that call OData count paths. This is a partial fix for https://github.com/microsoft/OpenAPI.NET.OData/issues/382.
* Adds `servicePrincipal`, `administrativeUnit`, and `device` derived types to `*-MgDirectoryDeletedItem*` commands in https://github.com/microsoftgraph/msgraph-metadata/pull/340
* Adds custom cmdlets for RSC configuration in https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/2001 and https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/1968
* Updates default output for common types in https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/2002
* Refreshes module with the latest API changes in …
> V2 RC 1 version bump

- src/readme.graph.md
Fixes #1486 by adding a directive to remove the extra `=` that's being applied by the AutoREST. This fix is limited to just Microsoft Graph PowerShell v2. A complete fix will be provided by https://github.com/Azure/autorest.powershell/issues/1025 in the code generator.
> Fix date assignment in Reports module.

- tools/ExamplesGenerator.ps1
Fixes #
This PR is a review of the example generator script responsible for importing examples from API reference docs. 
The script flags beta endpoint examples as wrong examples and deletes them from the markdown example files because they do not match the expected v2 examples with the new naming structure for beta endpoints. 
See comment on [this PR](https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/2022)
Beta examples from the "externalDocsUrl" openAPI parameter have not yet been updated to match the new naming structure for beta commands.
-  Modified script to write beta examples with "-MgBeta" and "Microsoft.Graph.Beta" prefix since the actual example coming from API reference doesn't have such prefixes.
- Added a test to validate the above scenario
> Examples Script Review

- src/Authentication/Authentication/Handlers/RequestHeaderHandler.cs
- src/Authentication/Authentication/Helpers/HttpHelpers.cs
- src/Authentication/Authentication/Helpers/RuntimeUtils.cs
- tools/Custom/HttpMessageLogFormatter.cs
Fixes #1916
- Clones request before reading/sanitizing request headers for logging to avoid thread safety issues when WinHttpHandler is used as the final handler (.NET Fx).
- Updates how `sdkVersion` and `client-request-id` are set on outgoing request.
> Fixes Request Header Logging When Using WinHttpHandler

- src/Authentication/Authentication.Core/Utilities/AuthenticationHelpers.cs
- src/Authentication/Authentication/test/Connect-MgGraph.Tests.ps1
﻿
Fixes https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/2035 by ensuring we write to PowerShell's debug stream on `Connect-MgGraph -Debug`:
``` powershell
➜ Connect-MgGraph -TenantId "thisdomaindoesnotexist.com" -UseDeviceAuthentication -Debug -ErrorAction SilentlyContinue
DEBUG: DeviceCodeCredential.Authenticate invoked. Scopes: [ User.Read ] ParentRequestId:
DEBUG: False MSAL 4.51.0.0 MSAL.NetCore .NET 7.0.5 Microsoft Windows 10.0.22621 [2023-05-25 00:10:59Z - 23771621-a234-4bbe-a286-fcd02e5568b2] MSAL MSAL.NetCore with assembly version '4.51.0.0'. CorrelationId(23771621-a234-4bbe-a286-fcd02e5568b2)
DEBUG: False MSAL 4.51.0.0 MSAL.NetCore .NET 7.0.5 Microsoft Windows 10.0.22621 [2023-05-25 00:10:59Z - 23771621-a234-4bbe-a286-fcd02e5568b2]
=== Request Data ===
Authority …
```
> Log MSAL events to debug stream

- tools/ExamplesGenerator.ps1
﻿
Fixes #2046 
This is the corresponding [PR ](https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/2049)to validate this fix 
- The script ensures that extraction of external docs link parameter from open API file is method driven (GET, POST, DELETE, PATCH)
- The script also maintains correct examples and discards wrong examples.
> V2 review examples generator script

- .azure-pipelines/weekly-preview-generation.yml
- .gitignore
This PR adds:
- A task to the weekly refresh pipeline script to ensure weekly artifacts branch is always synchronized with generation branch using `ours` merge strategy to avoid conflicts.
- `CodeSignSummary` files to `.GitIgnore`.
> Sync artifacts branch with generation branch

- src/Authentication/Authentication.Core/Utilities/AuthenticationHelpers.cs
﻿
Fixes https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1922
- Use `WithAuthority(authorityUrl)` when initializing MSAL applications to avoid the exception at https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1922. Some versions of MSAL will throw an exception in prod environments when `WithAuthority` and `WithTenantId` are specified on the same client. `GetAuthorityUrl(authContext);` will construct an authority URL that takes into account the specified tenant id.
See https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-client-application-configuration#how-to-specify-the-audience-in-your-codeconfiguration for more info.
> Use authorityUrl instead of tenantId when initializing MSAL

- .github/policies/msgraph-sdk-powershell-branch-protection.yml
Capture current policy state so that we can make versioned changes to branch protection policies. This will enable policy history, auditing, review, standardization, and templatization. We will update policy in later PR.
We can ignore the rule that states: `At least one value under RequiredStatusChecks must be specified when RequiresStrictStatusChecks is true.` or `RequiresStrictStatusChecks must be true when specifying RequiredStatusChecks.` This is getting removed. This is getting removed.
* https://github.com/microsoft/GitOps.Branches/pull/73
* https://github.com/microsoft/GitOps.Branches/issues/72
This branch protection policy will not take effect until https://github.com/microsoftgraph/.github/blob/main/policies/branch-protection-sdks.yml has been removed.
> chore: capture initial branch policy settings

- src/readme.graph.md
﻿
Fixes #2056
- Adds directive to change `base64Url` format to `byte`. The directive is needed to address the change that was made at https://github.com/Azure/autorest.powershell/pull/900. In AutoREST.PowerShell v3, properties are serialized as base64 when `format` is `byte` and `type` is string.
1. The base64 encoded properties should be declared as `base64` instead of `base64Url` in the OpenAPI document.
2. AutoREST.PowerShell should support serialization of `base64` format. As a workaround, we can declare string properties as `byte` to inform AutoREST.PowerShell that the property is a `base64` encoded. See https://github.com/Azure/azure-powershell/issues/17131#issuecomment-1042497183.
> Fixes base64 serialization

- src/Identity.Governance/Identity.Governance/examples/v1.0-beta/New-MgEntitlementManagementConnectedOrganization.md
﻿
Fixes #
- Fixed non-working, autogenerated example and added a new one
-
-
-
> Fixed non-working, autogenerated example and added a new one

- src/Groups/v1.0/test/New-MgGroup.Recording.json
- src/Groups/v1.0/test/New-MgGroup.Tests.ps1
- tools/Custom/HttpMessageLogFormatter.cs
- tools/Tests/loadEnv.ps1
﻿
Fixes #2064 by addressing thread safety intermittent bug in .NET framework when copying request content header.
- Updates how request content headers are copied when cloning a request.
> Update HttpRequest Clone Method

- .azure-pipelines/weekly-examples-update.yml
- tools/ImportExamples.ps1
﻿This PR updates script responsible for importing examples from api reference.
The changes conform to V2 examples that align with the naming convention of beta snippets.
The script has also been renamed to what it actually does.
> Updates examples import script to conform to v2 examples on Api reference docs

- src/Teams/beta/custom/TeamsAppPreApprovalPolicyConverter.cs
Add error handling for unsupported label types in chat conditions for preapprovals.
﻿
Fixes #
-
-
-
-
-
-
> Add error handling for unsupported label types in chat conditions for preapprovals

- .azure-pipelines/common-templates/create-pr.yml
- config/ModuleMetadata.json
- src/Applications/beta/Microsoft.Graph.Beta.Applications.psd1
- src/Authentication/Authentication/Microsoft.Graph.Authentication.nuspec
- src/Authentication/Authentication/Microsoft.Graph.Authentication.psd1
﻿Updated create pr script branch default value from features/2.0 to dev.
Updated metadata json's icon url to point to dev
> Update default branch from features/2.0 to dev

- .azure-pipelines/generation-templates/workload-modules.yml
- src/Users.Functions/Users.Functions.md
- tools/PostGeneration/FindDuplicateCommand.ps1
﻿
- Resolves duplicate command names in `Users.Functions` module using AutoREST directive.
- Adds `FindDuplicateCommand.ps1` to build pipelines. The script will detect duplicate command names across all modules.
> Resolve duplicate command names in `Users.Functions`

- config/ModuleMetadata.json
- src/readme.graph.md
﻿
Fixes #2313 
- Reverts AutoREST.PowerShell to v3.0.509. AutoREST.PowerShell v3.0.510 introduces a type that is only available in Azure SDK - https://www.npmjs.com/package/@autorest/powershell?activeTab=versions
- Bumps SDK version to 2.6.1
> Revert AutoREST.PowerShell to v3.0.509

- src/Authentication/Authentication.Core/Utilities/JwtHelpers.cs
- src/Authentication/Authentication.Test/Helpers/AuthenticationHelpersTests.cs
- src/Authentication/Authentication.Test/Helpers/JwtHelpersTests.cs
- src/Authentication/Authentication.Test/Microsoft.Graph.Authentication.Test.csproj
- src/Authentication/Authentication.Test/MockConstants.cs
Fixes #2386 due to https://stackoverflow.com/questions/66210139/why-my-valid-ms-access-token-cant-be-parsed-with-jwt-ms.
- Updates code to ensure we only decode JWT access tokens. Non-JWT tokens won't be decoded as they don't conform to https://tools.ietf.org/html/rfc7519.
- Adds unit tests to validate access token decoding.
> Fixes Invalid JWT token using a personal account

- src/Applications/v1.0/examples/Get-MgApplication.md
Updating permissions details.
﻿
Fixes #
-
-
-
-
-
-
> Update Get-MgApplication.md permissions details.

- src/Authentication/Authentication.Core/Microsoft.Graph.Authentication.Core.csproj
- src/Authentication/Authentication.Core/Utilities/AuthenticationHelpers.cs
- src/Authentication/Authentication/Microsoft.Graph.Authentication.nuspec
The current version bump of  Azure.Identity (1.10.2) introduced interactive browser errors when running ``Connect-MgGraph``
command. In some cases, the pop window with auth credential options fails to load.
This PR corrects that by rolling back to version 1.9.0 which doesn't have those errors
> Updates Azure.Identity and Azure.Identity.Broker package references to fix interactive browser credentials error

- src/Authentication/Authentication.Test/Helpers/EncodeUriPathTests.cs
- src/Authentication/Authentication/Cmdlets/InvokeMgGraphRequest.cs
- src/Authentication/Authentication/Helpers/EncodeUriPath.cs
﻿
Fixes #1947
-  Added function to escape data string/url encode path segments that have special characters like #. Results for both Absolute and relative uri are shown on the image below.
> Escapes special characters on path segments when using ``Invoke-MgGraphRequest``

- src/Teams/beta/custom/GetMgBetaTeamRscConfiguration_Get.cs
- src/Teams/beta/custom/MicrosoftGraphRscConfigurationState.cs
- src/Teams/beta/custom/RscConfigurationSynthesizer.cs
- src/Teams/beta/custom/SetMgBetaChatRscConfiguration_Update.cs
- src/Teams/beta/custom/SetMgBetaTeamRscConfiguration_Update.cs
﻿Change preapproval commandlets to not call directory settings APIs and manage preapprovals solely through permission grant policies.
Fixes #
-
-
-
-
-
-
> Change preapproval commandlets to not call directory settings apis

- .azure-pipelines/weekly-examples-update.yml
This PR updates Azure Devops service connection from the disabled one ``microsoftgraph`` to a working one ``MicrosoftDocs``. Currently being used by https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell to update PowerShell online reference docs.
> Updates Azure Devops service connection

- config/ModuleMetadata.json
Currently for all cmdlets one must specify the ``-Header`` parameter.
Updated AutoREST code generator to prevent this scenario.
> Patch Release. Ensures that ``-Header`` parameter is not mandatory

- src/Groups/beta/custom/NewMgBetaGroupMember_Create.cs
- src/Groups/beta/custom/NewMgBetaGroupMember_CreateExpanded.cs
- src/Groups/beta/custom/NewMgBetaGroupMember_CreateViaIdentity.cs
- src/Groups/beta/custom/NewMgBetaGroupMember_CreateViaIdentityExpanded.cs
- src/Groups/beta/custom/NewMgBetaGroupOwner_Create.cs
- src/Groups/beta/custom/NewMgBetaGroupOwner_CreateExpanded.cs
- src/Groups/beta/custom/NewMgBetaGroupOwner_CreateViaIdentity.cs
- src/Groups/beta/custom/NewMgBetaGroupOwner_CreateViaIdentityExpanded.cs
- src/Groups/v1.0/custom/NewMgGroupMember_Create.cs
- src/Groups/v1.0/custom/NewMgGroupMember_CreateExpanded.cs
- src/Groups/v1.0/custom/NewMgGroupMember_CreateViaIdentity.cs
- src/Groups/v1.0/custom/NewMgGroupMember_CreateViaIdentityExpanded.cs
- src/Groups/v1.0/custom/NewMgGroupOwner_Create.cs
- src/Groups/v1.0/custom/NewMgGroupOwner_CreateExpanded.cs
- src/Groups/v1.0/custom/NewMgGroupOwner_CreateViaIdentity.cs
- src/Groups/v1.0/custom/NewMgGroupOwner_CreateViaIdentityExpanded.cs
- src/Groups/v1.0/test/New-MgGroup.Tests.ps1
﻿
Fixes #2600 and #2394.
This change is based on the ``Invoke-MgGraphRequest`` design for capturing response headers by providing the same ``-RHV`` parameter
-  Adds Optional ``-RHV`` parameter.
-  Updates AutoREST submodule
> Adds an optional ``-RHV`` parameter that will assign response headers to a variable (Value provided to the optional RHV parameter)

- src/Authentication/Authentication/Models/GraphCommand.cs
- tools/PostGeneration/NewCommandMetadata.ps1
﻿
Fixes #2618 
- Updated NewCommandMetadata.ps1 to order permissions from graphexplorer api based on the least privilege property. (See image below)
- Updated GraphCommand.cs by adding ``IsLeastPrivilege`` property
> Orders permissions based on least privilege property value (``True`` or ``false``)

- src/Authentication/Authentication.Core/Microsoft.Graph.Authentication.Core.csproj
- src/Authentication/Authentication/Cmdlets/InvokeMgGraphRequest.cs
- src/Authentication/Authentication/Helpers/EncodeUriPath.cs
Fixes #1947 and ``Azure.Identity.Broker`` package conflict due to bumping of Azure Identity [here](https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/2675)
- Restricted escaping/URL encoding of special characters in path segments only. Uri with system query options should not URL encoded values. 
**Uri with OData system query options**
**Uri with special characters in path segments**
- Updated ``Azure.Identity.Broker`` due to interactive browser errors  (``Method 'get_UseDefaultBrokerAccount' in type 'Azure.Identity.Broker.InteractiveBrowserCredentialBrokerOptions' from assembly 'Azure.Identity.Broker, Version=1.0.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8' does not have an implementation``) as a result of bumping the ``Azure.Identity``. The version bump is based on …
> Restricts escaping of special characters to path segments only when using Invoke-MgGraphRequest and bumps ``Azure.Identity.Broker`` Library

- src/Authentication/Authentication.Core/Interfaces/IAuthContext.cs
- src/Authentication/Authentication.Core/Utilities/AuthenticationHelpers.cs
- src/Authentication/Authentication/Cmdlets/ConnectMgGraph.cs
- src/Authentication/Authentication/Constants.cs
- src/Authentication/Authentication/Models/AuthContext.cs
- src/Authentication/Authentication/test/Connect-MgGraph.Tests.ps1
﻿
Fixes #2698 
Adds a flag `SendCertificateChain` to `Connect-MgGraph` to send entire certificate chain while requesting access token. This allows subject name / issuer based auth.
`ClientCertificateCredentialOptions.SendCertificateChain` - https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/src/Credentials/ClientCertificateCredentialOptions.cs
> Add flag to send certificate chain for subject name / issuer based auth in Connect-MgGraph

- docs/BreakingChangeMigration.ps1
> Adds migration script for the breaking changes

- .github/policies/resourceManagement.yml
> update author feedback label

- tools/PostGeneration/NewCommandMetadata.ps1
Previous check would always set aliases to `null` when command metadata is being updated post-generation with the latest cmdlets.
Setting `null` aliases causes unit tests for aliasing in `Find-MgGraphCommand` to fail, breaking the build pipeline.
(Draft PR: pending a build pipeline run to update the command metadata.json with aliases)
> Fix bug when populating command alias value in command metadata JSON

- src/Authentication/Authentication/Cmdlets/InvokeMgGraphRequest.cs
﻿
Fixes #2795
- Resets session to original environment set during authentication. This is required especially when subsequent graph requests are not connecting to the default environment which has ``graph.microsoft.com`` as the base Uri (See ``PrepareUri`` method in ``InvokeMgGraphRequest.cs`` file)
> Resets graph environment session to its original state.

- .github/workflows/docker.yml
it looks like when we released v2, we broke docker images publishing. https://mcr.microsoft.com/en-us/product/microsoftgraph/powershell/tags
This adds a workflow to fix that
Related https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/1348
> fix: adds workflow to publish docker image

- .github/workflows/docker.yml
- Dockerfile
related https://github.com/microsoftgraph/msgraph-sdk-powershell/actions/runs/10197572950
docker manifest inspect mcr.microsoft.com/powershell returns linux/amd64 (I'm guessing the mac M users use that with QEMU), windows/amd64 (nobody uses that anymore AFAIK), linux/arm/v7 (this one I couldn't run, and I suggest we try to get feedback for a need for this before we invest further).
> fix: removes arm64v8 and armv7 platforms from docker since upstream image doesn't seem to support it

- .azure-pipelines/common-templates/esrp/codesign-nuget.yml
- .azure-pipelines/common-templates/esrp/codesign.yml
- .azure-pipelines/common-templates/esrp/strongname.yml
﻿
Fixes #2899
- Updates strongname, codesign and codesign-nuget files to use EsrpCodeSigning V5
**To do**
> Migration to ESRP V5

- src/Security/Security.md
Fixes #2961
Adds AutoRest directives to remove over generated cmdlets in Security module.
The following cmdlets won't be generated:
``Get-MgBetaSecurityAuditLog``
``Get-MgBetaSecurityAuditLogQuery``
``Get-MgBetaSecurityAuditLogQueryCount``
``Get-MgBeta`SecurityAuditLogQueryRecord``
``Get-MgBetaSecurityAuditLogQueryRecordCount``
> Adds AutoRest directives to remove over generated cmdlets

- src/Devices.CorporateManagement/beta/readme.md
Added directive to skip ``Update-MgBetaDeviceAppManagementMobileAppRelationship`` from cmdlet generation process causing overall failure in the Weekly refresh Open API pipeline.
> Fixes failure on the build pipeline.

- src/Authentication/Authentication/Cmdlets/InvokeMgGraphRequest.cs
- src/Authentication/Authentication/custom/common/Permissions.ps1
Fixes #2950 
The fix provided [here](https://github.com/microsoftgraph/msgraph-sdk-powershell/commit/815b63f7d6ff529880bf12441272850a35d2f293) only works once when an absolute uri is passed to ``Invoke-MgGraphRequest`` cmdlet after connecting to a national cloud environment.  Subsequent requests after the first successful one fails.
-  Added Microsoft graph context check in ``Find-MgGraphPermission`` in order to get the correct environment and extract the correct graph endpoint instead of using the default graph one (https://graph.microsoft.com) assigned to global environment. 
- Reset GraphSession environment back to its original state defined by the user.
- Check that ``Find-MgGraphPermission`` does not default the session to the global graph endpoint after connecting to a national …
> Fixes subsequent failures after first successful ``Invoke-MgGraphRequest`` run when using national cloud environments

- .azure-pipelines/ci-build.yml
closes https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/2990
Test run: https://microsoftgraph.visualstudio.com/Graph%20Developer%20Experiences/_build/results?buildId=166516&view=results
> Use 1ES pipeline template for build pipeline

- src/Calendar/Calendar.md
﻿
Fixes #
- Adds Autorest directive to remove duplicate ``Get-MgUserCalendarSchedule`` cmdlet in the Calendar module failing during generation due to multiple parameter types in the request body. The cmdlet also already exists in the ``User.Actions`` module.
> Removes duplicate generated cmdlet blocking cmdlet builds during Weekly Open Api refresh

- tools/DownloadOpenApiDoc.ps1
- tools/PostGeneration/NewCommandMetadata.ps1
﻿
Fixes #3020 
The change ensures that calls to fetch permissions and slicing of open API file based on tags, points to DevX API hosted in Torus.
> Updates endpoint to use Devx API in Torus

- CONTRIBUTING.md
fixing broken link
﻿
Fixes #
-
-
-
-
-
-
> Update CONTRIBUTING.md - fixing link

- src/Security/Security.md
Fixes #3051 
Re-enabled generation of the below cmldets whose endpoints are now supported.
Get-MgBetaSecurityAuditLog
Get-MgBetaSecurityAuditLogQuery
Get-MgBetaSecurityAuditLogQueryCount
Get-MgBeta`SecurityAuditLogQueryRecord
Get-MgBetaSecurityAuditLogQueryRecordCount
> Re-enables generation of Get cmdlets for attack simulation.

- .azure-pipelines/common-templates/install-tools.yml
﻿Fixes #3073 
Drops unsupported net 6 and net 7 from the CI pipeline.
> Drop unsupported net 6 and net 7 

- src/Applications/beta/examples/Get-MgBetaApplicationDelta.md
- src/Applications/beta/examples/Get-MgBetaServicePrincipalSynchronizationTemplate.md
- src/Applications/v1.0/examples/Get-MgServicePrincipalSynchronizationTemplate.md
- src/Bookings/beta/examples/Initialize-MgBetaBackupRestoreProtectionPolicy.md
- src/Bookings/beta/examples/Invoke-MgBetaDeactivateSolutionBackupRestoreProtectionPolicy.md
- src/Bookings/v1.0/examples/Invoke-MgDeactivateSolutionBackupRestoreProtectionPolicy.md
- src/CloudCommunications/beta/examples/New-MgBetaCommunicationCall.md
- src/CloudCommunications/v1.0/examples/New-MgCommunicationCall.md
- src/Identity.DirectoryManagement/beta/examples/Get-MgBetaDirectoryRoleDelta.md
- src/Identity.DirectoryManagement/v1.0/examples/Get-MgDirectoryRoleDelta.md
- src/Identity.Governance/beta/examples/Get-MgBetaEntitlementManagementAccessPackageAssignment.md
- src/Identity.Governance/beta/examples/Get-MgBetaEntitlementManagementAssignmentRequest.md
- src/Identity.Governance/beta/examples/Get-MgBetaRoleManagementDirectoryRoleAssignment.md
- src/Identity.Governance/beta/examples/Get-MgBetaRoleManagementDirectoryTransitiveRoleAssignment.md
- src/Identity.Governance/beta/examples/New-MgBetaRoleManagementDirectoryRoleAssignment.md
- src/Identity.Governance/v1.0/examples/Get-MgEntitlementManagementAssignment.md
- src/Identity.Governance/v1.0/examples/Get-MgEntitlementManagementAssignmentRequest.md
- src/Identity.Governance/v1.0/examples/Get-MgRoleManagementDirectoryRoleAssignment.md
- src/Identity.Governance/v1.0/examples/New-MgRoleManagementDirectoryRoleAssignment.md
- src/Identity.SignIns/beta/examples/Get-MgBetaServicePrincipalRiskDetection.md
- src/Identity.SignIns/v1.0/examples/Get-MgServicePrincipalRiskDetection.md
- src/Search/beta/examples/Set-MgBetaExternalConnectionItem.md
- src/Search/v1.0/examples/Set-MgExternalConnectionItem.md
- src/Teams/beta/examples/New-MgBetaChatMessage.md
- src/Teams/beta/examples/New-MgBetaTeamChannelMessage.md
- src/Teams/v1.0/examples/Get-MgChatInstalledApp.md
- src/Teams/v1.0/examples/New-MgChatMessage.md
- src/Teams/v1.0/examples/New-MgTeamChannelMessage.md
- tools/ImportExamples.ps1
> Removes unnecessary '#' characters in example descriptions

- src/Authentication/Authentication.Core/Microsoft.Graph.Authentication.Core.csproj
part of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/2774
Unblocks 
- conflicts with ExchangeOnlineManagement caused by using System.Text.Json 6.x
- security update since v6.x has CVEs
~EXO failing with a different error that doesn't signal conflicts, reached out to partner team to clarify~
Update: Issue was in my app registration permissions for EXO
Reference docs to set up app-only auth with EXO: https://learn.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps
Importing MgGraph before EXO & Az.Accounts
Import EXO before MgGraph & Az.Accounts
> feat: add direct dependency on System.Text.Json

- src/Identity.SignIns/beta/examples/New-MgBetaInvitation.md
- src/Identity.SignIns/v1.0/examples/New-MgInvitation.md
> Updated examples for ``New-MgInvitaiton`` and ``New-MgBetaInvitation``

- src/Security/Security.md
Fixes #3065 
Based on the documentation provided [here](https://learn.microsoft.com/en-us/graph/api/simulation-get?view=graph-rest-beta&tabs=http), the correct path is ``/security/attackSimulation/simulations``.
> Adds directive to remove invalid path. ``/security/attackSimulation``

- .azure-pipelines/common-templates/install-tools.yml
- src/Authentication/Authentication.Core/Microsoft.Graph.Authentication.Core.csproj
- src/Authentication/Authentication.Core/Utilities/AuthenticationHelpers.cs
- src/Authentication/Authentication.Test/Microsoft.Graph.Authentication.Test.csproj
- src/Authentication/Authentication/Helpers/HttpHelpers.cs
- src/Authentication/Authentication/build-module.ps1
- src/Authentication/Authentication/test/Connect-MgGraph.Tests.ps1
Fixes #2997 
The obsolete compression handler has also been dropped since kiota now relies on HttpClientHandler.
It also drops unsupported net6 as the target framework.
> Bumps versions for Azure.Identity, Azure.Identity.Broker and Microsoft.Graph.Core

- src/Teams/Teams.md
Fixes #2585
The Api path is undocumented and any request to it responds with http status code 404.
> Adds directive to remove invalid path``/teams/{team-id}/channels/{channel-id}/messages/$count``

- config/ModulesMapping.jsonc
- openApiDocs/beta/Identity.DirectoryManagement.yml
- openApiDocs/v1.0/Identity.DirectoryManagement.yml
Fixes #2737
This PR updates module mapping file by adding the missing tag `tenantRelationships.tenantRelationship.Functions` to the `config/ModulesMapping.jsonc` file. It also updates `Identity.Directorymanagement.yml` by adding the missing path `/tenantRelationships/microsoft.graph.findTenantInformationByDomainName(domainName=''{domainName}'')`
> Updates module mapping file to add missing tag ``tenantRelationships.tenantRelationship.Functions``

- src/Sites/Sites.md
Updates sites directive to remove patch operation for `/sites/{site-id}/pages/{baseSitePage-id}` which is undocumented and returns http status code 404.
This partly fixes issue #2919
> Update sites directive to remove patch operation for `/sites/{site-id}/pages/{baseSitePage-id}`

- .azure-pipelines/generation-templates/authentication-module.yml
- src/readme.graph.md
- tools/Custom/JsonExtensions.cs
- tools/Tests/JsonUtilitiesTest/JsonExtensionsTests.cs
- tools/Tests/JsonUtilitiesTest/JsonUtilitiesTest.csproj
﻿
Fixes #2609 and #3008 
- Adds autorest directive to ensure that null valued properties are not omitted by default.
- Adds a custom JsonExtensions class containing an extension method that ensures properties explicitly defined as null in a PowerShell session are retained 
- Adds test project to test the above custom class.
This PR has a dependency on the autorest update done here which is part of addressing the issue here https://github.com/microsoftgraph/autorest.powershell/pull/9
> Allows serialization of null valued properties.

- tools/PostGeneration/NewCommandMetadata.ps1
Fixes #3122 
**Before**
**Expected result after fix**
> Removes sorting by unique name because it omits permissions with the same name but different permission type

- tools/Custom/JsonExtensions.cs
- tools/Tests/JsonUtilitiesTest/JsonExtensionsTests.cs
Fixes #3149 and #3154 
Updates tests to include `/` scenarios
> Ensures property values that have `/` are not modified to have them removed

- tools/Custom/JsonExtensions.cs
- tools/Tests/JsonUtilitiesTest/JsonExtensionsTests.cs
Fixes #3157
Fixes #3158 
Fixes #3159 
Fixes #3160
Files changed
1.  JsonExtenstions file updated to handle deeply nested json objects and arrays. 
2. JsonExtensionTest file updated with test scenarios to validate the above change.
Example of affected cmdlet is ```Send-MgUserMail`` as reported by customer. After this change, the cmdlet should be able to process and send attachments.
> Updated Json extension class to handle deeply nested object and array

- .azure-pipelines/common-templates/install-tools.yml
- src/Authentication/Authentication.Core/Microsoft.Graph.Authentication.Core.csproj
- src/Authentication/Authentication/build-module.ps1
This PR rolls back the authentication module to .NET 6 due to the breaking change in the .NET SDK version 8.x. which is not compatible with Azure Automation Run Book's PowerShell 7.2 version.
> Roll back to .NET 6

- src/Devices.ServiceAnnouncement/Devices.ServiceAnnouncement.md
﻿
Fixes #3250 
The cmdlets highlighted in the image below are unsupported because serviceAnnouncement Apis do not support POST, PATCH, PUT and DELETE operations.
- Added AutoRest directives to remove unsupported cmdlets
- Update metadata file.
> Added directives to disable generation of invalid Service Announcement cmdlets

- src/DeviceManagement/DeviceManagement.md
This PR excludes the `deviceManagement_windowsPrivacyAccessControl` resource from being generated into the DeviceManagement module. This is necessary because it otherwise is "merged" with the `Get-MgBetaDeviceManagementDeviceConfiguration` cmdlet, therefore resulting in a broken parameter set resolution. 
`deviceManagement_windowsPrivacyAccessControl` is assigned the `Get-MgBetaDeviceManagementDeviceConfiguration` command in `MgCommandMetadata.json`. There, also the variants `Access`, `AccessExpanded`, `AccessViaIdentity` and `AccessViaIdentityExpanded` are defined. Having this definition there forces the merge of the default `Get-MgBetaDeviceManagementDeviceConfiguration` cmdlet with this object, although this should have a dedicated cmdlet, or even better, simply be excluded because it …
> Remove WindowsPrivacyAccessControl from module generation

- config/ModuleMetadata.json
- openApiDocs/beta/BackupRestore.yml
Patch Beta BackupRestore module
> Patch BackupRestore in Beta only 
